#!/usr/bin/env node
/**
 * Bundle BrainCore: shared LifeOS modules + main.source.js (core) → main.js
 * Also writes styles.css (Obsidian loads it; no runtime <style> injection).
 *
 * Default edition is trial24h so `npm run build` matches the community Release main.js
 * (Scorecard build verification). Pass personal|commercial|publicFree|trial24h to override.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { readLifeOsSidebarInsetCss } from "./lifeos-shared-sidebar.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

const EDITION_PROFILES = {
  personal: { profile: "personal", trial: 0, license: false, edition: "personal" },
  commercial: { profile: "commercial", trial: 0, license: true, edition: "public" },
  publicFree: { profile: "commercial", trial: 0, license: false, edition: "public" },
  // Community / Scorecard default — same flags as dist 「48小时体验版」
  trial24h: { profile: "commercial", trial: 48, license: true, edition: "public" },
};

const editionArg = process.argv[2] || process.env.BC_EDITION || "trial24h";
const editionCfg = EDITION_PROFILES[editionArg];
if (!editionCfg) {
  console.error(`Unknown edition "${editionArg}". Use: ${Object.keys(EDITION_PROFILES).join(", ")}`);
  process.exit(1);
}

function read(name) {
  return fs.readFileSync(path.join(root, name), "utf8");
}

function buildUsageGuideModule(usageBody, shortcutsBody) {
  const template = read("src/usage-guide.js");
  return template
    .replace("__USAGE_GUIDE_BODY__", JSON.stringify(usageBody))
    .replace("__SHORTCUTS_GUIDE_BODY__", JSON.stringify(shortcutsBody));
}

function applyEditionFlags(code, cfg) {
  return code
    .replace(/const PLUGIN_WEEKLY_PROFILE = "[^"]+";/, `const PLUGIN_WEEKLY_PROFILE = "${cfg.profile}";`)
    .replace(/const PLUGIN_TRIAL_HOURS = \d+;/, `const PLUGIN_TRIAL_HOURS = ${cfg.trial};`)
    .replace(/const PLUGIN_LICENSE_REQUIRED = (true|false);/, `const PLUGIN_LICENSE_REQUIRED = ${cfg.license};`)
    .replace(/const PLUGIN_EDITION = "[^"]+";/, `const PLUGIN_EDITION = "${cfg.edition}";`);
}

function writeStylesCss(momentsCssRaw) {
  let shared = read("src/css/lifeos-ui-shared.css");
  const marker = "/* __LIFEOS_SIDEBAR_INSET_CSS__ */";
  if (!shared.includes(marker)) {
    throw new Error(`src/css/lifeos-ui-shared.css missing placeholder ${marker}`);
  }
  shared = shared.replace(marker, readLifeOsSidebarInsetCss());
  const parts = [
    "/* BrainCore LifeOS — generated by scripts/build.mjs; do not edit by hand */",
    shared,
    read("src/css/lifeos-suite.css"),
    read("src/css/bc-settings-tab-layout.css"),
    read("src/css/update-notice.css"),
    read("src/css/set-heading.css"),
    read("src/css/bc-capture-modal.css"),
    read("src/css/bc-dashboard.css"),
    read("src/css/bc-weekly.css"),
    read("src/css/bc-material-modal.css"),
    read("src/css/bc-clip-confirm.css"),
    read("src/css/bc-today-delta.css"),
    read("src/css/bc-ios-quick.css"),
    "/* —— Moments —— */",
    momentsCssRaw,
  ];
  const out = parts.map((p) => String(p).trim()).filter(Boolean).join("\n\n") + "\n";
  fs.writeFileSync(path.join(root, "styles.css"), out);
  return out.length;
}

const manifest = JSON.parse(read("manifest.json"));
const core = read("main.source.js");

const guideBody = fs.readFileSync(path.join(root, "docs/usage-guide-body.md"), "utf8");
const shortcutsGuideBody = fs.readFileSync(path.join(root, "docs/BrainCore快捷指令使用指南.md"), "utf8");

let patchedCore = core.replace(
  /const PLUGIN_VERSION = "[^"]+";/,
  `const PLUGIN_VERSION = "${manifest.version}";`
);
patchedCore = applyEditionFlags(patchedCore, editionCfg);

const fileWallTemplatePath = path.join(root, "docs/templates/文件墙.md");
if (!fs.existsSync(fileWallTemplatePath)) {
  throw new Error("缺少文件墙模板: docs/templates/文件墙.md");
}
const fileWallTemplate = fs.readFileSync(fileWallTemplatePath, "utf8");
if (!fileWallTemplate.includes("最近上传") || !fileWallTemplate.includes("custom-lib-wrapper")) {
  throw new Error("文件墙模板不完整（缺少最近上传 / custom-lib-wrapper）");
}
if (!patchedCore.includes('const FILE_WALL_NOTE_TEMPLATE = "";')) {
  throw new Error("main.source.js 缺少 FILE_WALL_NOTE_TEMPLATE 占位");
}
patchedCore = patchedCore.replace(
  'const FILE_WALL_NOTE_TEMPLATE = "";',
  `const FILE_WALL_NOTE_TEMPLATE = ${JSON.stringify(fileWallTemplate)};`
);

const momentsBaseCss = read("src/moments-memoria/styles.css");
const momentsCssRaw = [
  momentsBaseCss.trimEnd(),
  read("src/moments-memoria/ui-contract.css"),
  read("src/moments-memoria/share-contract.css"),
].join("\n");
const momentsCssExtra = `
.workspace-leaf-content[data-type="braincore-moments-view"] .view-content{padding:0;overflow:hidden;display:flex;flex-direction:column}
.workspace-leaf-content[data-type="braincore-moments-year-view"] .view-content{padding:44px 36px 64px;overflow-y:auto;overflow-x:hidden;display:block}
.workspace-leaf-content[data-type="braincore-moments-stats-view"] .view-content{padding:48px 56px 64px;overflow-y:auto;overflow-x:hidden;display:block}
@media(max-width:520px){.workspace-leaf-content[data-type="braincore-moments-stats-view"] .view-content{padding:24px 16px 48px}}
.memoria-list-meta-left{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.memoria-sort-btn,.memoria-quick-filter{display:inline-flex;align-items:center;justify-content:center;width:36px;height:36px;min-width:36px;min-height:36px;padding:0;border-radius:50%;box-sizing:border-box}
`;
const momentsCssForStyles = momentsCssRaw + momentsCssExtra;
// Keep a tiny stub so older bridges that reference BCM_MOMENTS_CSS still parse;
// runtime inject is a no-op — CSS ships via styles.css.
const bcmMomentsCssConst = `const BCM_MOMENTS_CSS = "";\n`;
const momentsCoreBundle = read("src/moments-core.bundle.js");
const momentsBridge = read("src/moments.js");

if (patchedCore.includes("module.exports = BrainCorePlugin")) {
  const momentsInject = `${bcmMomentsCssConst}\n${momentsCoreBundle}\n${momentsBridge}\nmodule.exports = BrainCorePlugin;`;
  patchedCore = patchedCore.replace(
    "module.exports = BrainCorePlugin;",
    () => momentsInject
  );
} else {
  console.warn("warn: module.exports not found; appending moments modules");
  patchedCore += "\n" + bcmMomentsCssConst + momentsCoreBundle + momentsBridge;
}

const stylesBytes = writeStylesCss(momentsCssForStyles);

const parts = [
  read("src/lifeos-ui-shared.js"),
  read("src/braincore-global-bridge.js"),
  read("src/update-sections.js"),
  read("src/lifeos-suite.js"),
  read("src/update-notice.js"),
  buildUsageGuideModule(guideBody, shortcutsGuideBody),
  read("src/bc-settings-tab-layout.js"),
  read("src/quote-index.js"),
  patchedCore,
];

// Do not stamp LIFEOS_RELEASE to "today" — keep source value for byte-stable rebuilds.
fs.writeFileSync(path.join(root, "main.js"), parts.join("\n"));
console.log(
  `Built main.js (${(parts.join("").length / 1024).toFixed(1)} KB) + styles.css (${(stylesBytes / 1024).toFixed(1)} KB) edition=${editionArg}`
);
